
service: serverless-todo-rest-api
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: arn:aws:dynamodb:us-east-1:*:*

resources:
  Resources:
    TodosTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          -
            AttributeName: id
            AttributeType: S
        KeySchema:
          -
            AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: 'todos'

functions:
  create:
    handler: src/handler/createTodo.createTodo
    events:
      - http:
          path: todos
          method: post
          cors: true
  list:
    handler: src/handler/listTodo.listTodo
    events:
      - http:
          path: todos
          method: get
          cors: true
  get:
    handler: src/handler/getTodo.getTodo
    events:
      - http:
          path: todos/{id}
          method: get
          cors: true
  update:
    handler: src/handler/updateTodo.updateTodo
    events:
      - http:
          path: todos/{id}
          method: put
          cors: true
  delete:
    handler: src/handler/deleteTodo.deleteTodo
    events:
      - http:
          path: todos/{id}
          method: delete
          cors: true